### ISSUE TITLE
Como administrador, quiero registrar las máquinas disponibles en el gimnasio para que los usuarios y entrenadores puedan conocerlas.

### ISSUE THREAD

**Issue by asaygom** [asaygom/Final-project-4Geeks-User-Strories#23]

**Comment by olivarescroc** [comment]
- [ ] Debe iniciar sesión como administrador.
- [ ] Debe tener acceso al dashboard de administración
- [x] Debe haber una sección específica para administrar las máquinas del gimnasio.
- [x] Debe ser capaz de añadir una nueva máquina proporcionando detalles como: nombre, descripción, activa o inactiva
- [x] Debe ser capaz de editar los detalles de una máquina existente.
- [x] Debe ser capaz de eliminar una máquina del registro.
- [x] Debe ser capaz de ver una lista de todas las máquinas registradas con sus detalles.
- [x] Los cambios en las máquinas deben reflejarse en tiempo real en la aplicación para los usuarios y entrenadores.

**Comment by asaygom** [comment]
Falta configurar las vistas en base al rol
